Adding support for DP-net
SWKS-AIS-DSP/tflite-micro pull request #4
Opened 2022-05-23 17:46 UTC by MerlinCarson

Added registration code for LSTM and Squared Difference Ops.
Added test for DP-net

2022-05-23 19:59 UTC, spencer-hann requested changes

2022-05-23 19:59 UTC, spencer-hann commented on tensorflow/lite/micro/examples/dp_net/dp_net_test.cc
> +	std::cout << data_file << " loaded." << std::endl;
We may want to use something more robust than a `NO_COUT` macro, it can be easy to miss.

2022-05-23 19:59 UTC, spencer-hann commented on tensorflow/lite/micro/examples/dp_net/dp_net_test.cc
> +  y_tfl = new float[output_len];
This memory never gets deallocated.  Also, these pointers get passed to a function that may call `exit`.  Some kind of RAII type would be safer here.

2022-05-23 20:10 UTC, spencer-hann approved these changes

2022-05-24 18:20 UTC, MerlinCarson commented on tensorflow/lite/micro/examples/dp_net/dp_net_test.cc
> +  y_tfl = new float[output_len];
Added freeing dynamically allocated memory

2022-05-24 18:22 UTC, merged